//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaelApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseAkaelEntities : DbContext
    {
        public DatabaseAkaelEntities()
            : base("name=DatabaseAkaelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<AreaProcesso> AreaProcesso { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<MetaEspecifica> MetaEspecifica { get; set; }
        public virtual DbSet<MetaGenerica> MetaGenerica { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<NivelCapacidade> NivelCapacidade { get; set; }
        public virtual DbSet<NivelMaturidade> NivelMaturidade { get; set; }
        public virtual DbSet<PraticaEspecifica> PraticaEspecifica { get; set; }
        public virtual DbSet<PraticaEspecificaProdutoTrabalho> PraticaEspecificaProdutoTrabalho { get; set; }
        public virtual DbSet<ProdutoTrabalho> ProdutoTrabalho { get; set; }
    }
}
