//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaGenerica
    {
        public int IdMetaGenerica { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int IdNivelCapacidade { get; set; }
        public int IdModelo { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual NivelCapacidade NivelCapacidade { get; set; }
    }
}
