//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaelApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProdutoTrabalho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutoTrabalho()
        {
            this.PraticaEspecificaProdutoTrabalho = new HashSet<PraticaEspecificaProdutoTrabalho>();
        }
    
        public int IdProdutoTrabalho { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Template { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public int IdPraticaEspecifica { get; set; }
    
        public virtual PraticaEspecifica PraticaEspecifica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraticaEspecificaProdutoTrabalho> PraticaEspecificaProdutoTrabalho { get; set; }
    }
}
